version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - todo_post_data:/var/lib/postgresql/data
      - ./schema/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=todo
      - POSTGRES_SSL_MODE=disable
    networks:
      my_net:
        ipv4_address: 192.168.100.2

networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
volumes:
  todo_post_data: